/*
# Seed products table

Populates `products` with the 18 catalog items currently hardcoded in
src/data/products.ts, so the storefront can be migrated to read from Supabase.

Uses ON CONFLICT (id) DO UPDATE so this migration is safe to re-run.
*/

INSERT INTO products
  (id, name, category, price, old_price, rating, review_count, images, material, gemstone, collection, is_new, is_best_seller, in_stock, sizes, description, details)
VALUES
  ('aurora-solitaire', 'Aurora Solitaire Ring', 'Rings', 2890, NULL, 4.9, 214, ARRAY['https://images.pexels.com/photos/12290109/pexels-photo-12290109.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/12427696/pexels-photo-12427696.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/11745298/pexels-photo-11745298.jpeg?auto=compress&cs=tinysrgb&w=900'], 'Platinum', 'Diamond', 'Bridal Collection', false, true, true, ARRAY['4','5','6','7','8','9'], 'A single brilliant-cut diamond cradled in a hand-finished platinum band. The Aurora is our most beloved engagement ring — luminous, architectural, eternal.', ARRAY['1.2ct brilliant-cut diamond','Conflict-free, VS1 clarity','Hand-polished platinum band','Engravable inner band']),
  ('celeste-halo', 'Céleste Halo Ring', 'Rings', 3450, 3990, 4.8, 156, ARRAY['https://images.pexels.com/photos/2732096/pexels-photo-2732096.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/21928764/pexels-photo-21928764.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/13524236/pexels-photo-13524236.jpeg?auto=compress&cs=tinysrgb&w=900'], 'White Gold', 'Diamond', 'Diamond Collection', true, true, true, ARRAY['4','5','6','7','8','9'], 'A pavé halo of diamonds surrounds a centre stone, catching light from every angle. Céleste is crafted for those who believe more is more.', ARRAY['0.9ct centre diamond','Pavé halo, 38 stones','18k white gold','Signature engraved profile']),
  ('lumiere-eternity', 'Lumière Eternity Band', 'Rings', 1980, NULL, 4.7, 98, ARRAY['https://images.pexels.com/photos/31728371/pexels-photo-31728371.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5737285/pexels-photo-5737285.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/9080072/pexels-photo-9080072.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'Diamond', 'Bridal Collection', false, true, true, ARRAY['4','5','6','7','8','9'], 'A continuous circle of pavé diamonds — a quiet symbol of a love without end. Stack it or wear it alone.', ARRAY['Full-circle pavé diamonds','18k yellow gold','Comfort-fit interior','0.75ct total weight']),
  ('seraphine-pearl', 'Séraphine Pearl Ring', 'Rings', 1240, NULL, 4.6, 64, ARRAY['https://images.pexels.com/photos/1395305/pexels-photo-1395305.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33343007/pexels-photo-33343007.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5987971/pexels-photo-5987971.jpeg?auto=compress&cs=tinysrgb&w=900'], 'Rose Gold', 'Pearl', 'Statement Pieces', false, false, true, ARRAY['4','5','6','7','8','9'], 'A luminous Akoya pearl cradled by rose-gold petals. Séraphine blends old-world romance with contemporary craft.', ARRAY['8mm Akoya pearl','18k rose gold','Diamond accent shoulders','Made to order']),
  ('aria-pendant', 'Aria Pendant Necklace', 'Necklaces', 1675, NULL, 4.9, 187, ARRAY['https://images.pexels.com/photos/21787515/pexels-photo-21787515.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/9173459/pexels-photo-9173459.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/15925159/pexels-photo-15925159.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'Diamond', 'Everyday Elegance', false, true, true, ARRAY['14"','16"','18"','20"'], 'A single diamond suspended on a delicate 18k gold chain. The Aria sits just below the collarbone — subtle, radiant, endlessly wearable.', ARRAY['0.3ct solitaire diamond','18k gold cable chain','Adjustable 16–20 inch','Lobster clasp']),
  ('soleil-layered', 'Soleil Layered Necklace', 'Necklaces', 890, NULL, 4.7, 142, ARRAY['https://images.pexels.com/photos/13924051/pexels-photo-13924051.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7514818/pexels-photo-7514818.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/4735888/pexels-photo-4735888.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'None', 'Minimalist Collection', true, false, true, ARRAY['14"','16"','18"','20"'], 'Two gold chains of varying length create effortless dimension. Pre-layered and ready to wear — the everyday signature.', ARRAY['Two-strand layered design','18k gold vermeil','Tangle-free links','16 + 18 inch']),
  ('noe-pearl-strand', 'Noé Pearl Strand', 'Necklaces', 1450, NULL, 4.8, 73, ARRAY['https://images.pexels.com/photos/8774780/pexels-photo-8774780.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7514818/pexels-photo-7514818.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/12133990/pexels-photo-12133990.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'Pearl', 'Statement Pieces', false, false, true, ARRAY['14"','16"','18"','20"'], 'A graduated strand of freshwater pearls, hand-knotted on silk and finished with an 18k gold clasp. An heirloom in the making.', ARRAY['Graduated freshwater pearls','Hand-knotted silk thread','18k gold filigree clasp','18 inch']),
  ('elysee-drop', 'Élysée Drop Earrings', 'Earrings', 2150, NULL, 4.9, 131, ARRAY['https://images.pexels.com/photos/5370644/pexels-photo-5370644.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5737290/pexels-photo-5737290.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2849743/pexels-photo-2849743.jpeg?auto=compress&cs=tinysrgb&w=900'], 'White Gold', 'Diamond', 'Diamond Collection', false, true, true, '{}', 'Marquise-cut diamonds cascade in a graceful drop. The Élysée moves with you, scattering light at every turn.', ARRAY['Marquise diamond drops','18k white gold','1.1ct total weight','Post and clutch backing']),
  ('margaux-studs', 'Margaux Diamond Studs', 'Earrings', 1290, NULL, 4.8, 209, ARRAY['https://images.pexels.com/photos/20943476/pexels-photo-20943476.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5737290/pexels-photo-5737290.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/35961143/pexels-photo-35961143.jpeg?auto=compress&cs=tinysrgb&w=900'], 'Platinum', 'Diamond', 'Everyday Elegance', false, true, true, '{}', 'The essential pair. Round brilliant diamonds set in platinum four-prong settings — the studs you will reach for every morning.', ARRAY['0.5ct each, VS1 clarity','Platinum four-prong setting','Screw-back closure','GIA certified']),
  ('ophelia-hoops', 'Ophelia Pavé Hoops', 'Earrings', 980, NULL, 4.6, 88, ARRAY['https://images.pexels.com/photos/10976654/pexels-photo-10976654.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/35270159/pexels-photo-35270159.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/28389453/pexels-photo-28389453.jpeg?auto=compress&cs=tinysrgb&w=900'], 'Rose Gold', 'Diamond', 'Minimalist Collection', true, false, true, '{}', 'Slim rose-gold hoops dusted with pavé diamonds. Light enough for all-day wear, luminous enough for evening.', ARRAY['Pavé diamond hoops','18k rose gold','20mm diameter','Hinged snap closure']),
  ('vivienne-emerald', 'Vivienne Emerald Drops', 'Earrings', 2780, NULL, 4.7, 41, ARRAY['https://images.pexels.com/photos/7258925/pexels-photo-7258925.png?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7981566/pexels-photo-7981566.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5370642/pexels-photo-5370642.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'Emerald', 'Statement Pieces', false, false, true, '{}', 'Colombian emeralds framed by diamond halos. Vivienne is a jewel-box centrepiece — vivid, regal, unforgettable.', ARRAY['2 Colombian emeralds, 1.8ct','Diamond halo surround','18k yellow gold','Lever-back closure']),
  ('alma-tennis', 'Alma Tennis Bracelet', 'Bracelets', 3650, NULL, 4.9, 112, ARRAY['https://images.pexels.com/photos/20141640/pexels-photo-20141640.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5370647/pexels-photo-5370647.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/34362938/pexels-photo-34362938.jpeg?auto=compress&cs=tinysrgb&w=900'], 'White Gold', 'Diamond', 'Diamond Collection', false, true, true, ARRAY['S','M','L'], 'A continuous line of brilliant-cut diamonds in white gold. The Alma tennis bracelet is the definition of understated opulence.', ARRAY['3.2ct total diamond weight','18k white gold','Double-safety clasp','Available in S/M/L']),
  ('riviera-chain', 'Riviera Gold Chain', 'Bracelets', 1190, NULL, 4.7, 95, ARRAY['https://images.pexels.com/photos/14509640/pexels-photo-14509640.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/3641059/pexels-photo-3641059.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/37573129/pexels-photo-37573129.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'None', 'Gold Collection', false, false, true, ARRAY['S','M','L'], 'A substantial 18k gold curb chain with a polished lobster clasp. Wear it solo or stack with the Lumière Eternity Band.', ARRAY['18k solid gold','7mm curb links','Lobster clasp','Made in Italy']),
  ('josephine-charm', 'Joséphine Charm Bracelet', 'Bracelets', 760, NULL, 4.5, 57, ARRAY['https://images.pexels.com/photos/34399115/pexels-photo-34399115.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/34399059/pexels-photo-34399059.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/34399116/pexels-photo-34399116.jpeg?auto=compress&cs=tinysrgb&w=900'], 'Rose Gold', 'Diamond', 'Minimalist Collection', true, false, true, ARRAY['S','M','L'], 'A delicate rose-gold chain anchored by a single teardrop charm. Joséphine is the everyday piece you never take off.', ARRAY['18k rose gold','Teardrop diamond charm','Adjustable length','Spring-ring clasp']),
  ('meridian-chrono', 'Meridian Chronograph', 'Watches', 4200, NULL, 4.8, 63, ARRAY['https://images.pexels.com/photos/10591429/pexels-photo-10591429.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/25052866/pexels-photo-25052866.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8854152/pexels-photo-8854152.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'None', 'Statement Pieces', false, true, true, ARRAY['32mm','36mm','40mm'], 'A Swiss-made chronograph in 18k gold with a hand-stitched leather strap. The Meridian is precision wrapped in warmth.', ARRAY['Swiss automatic movement','18k gold case','Sapphire crystal','Italian leather strap']),
  ('eclipse-auto', 'Eclipse Automatic', 'Watches', 2890, NULL, 4.7, 48, ARRAY['https://images.pexels.com/photos/28135838/pexels-photo-28135838.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33277498/pexels-photo-33277498.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/22032439/pexels-photo-22032439.jpeg?auto=compress&cs=tinysrgb&w=900'], 'Platinum', 'None', 'Minimalist Collection', true, false, true, ARRAY['32mm','36mm','40mm'], 'A platinum case, a midnight dial, an exhibition caseback. The Eclipse is quiet luxury for the wrist.', ARRAY['Swiss automatic movement','Platinum case','Exhibition caseback','Alligator strap']),
  ('heritage-roman', 'Heritage Roman', 'Watches', 1980, 2350, 4.6, 39, ARRAY['https://images.pexels.com/photos/15671805/pexels-photo-15671805.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/3419331/pexels-photo-3419331.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/9267840/pexels-photo-9267840.jpeg?auto=compress&cs=tinysrgb&w=900'], '18k Gold', 'None', 'Gold Collection', false, false, true, ARRAY['32mm','36mm','40mm'], 'Roman numerals, a gold bezel, and a sunray dial. The Heritage is a classic dress watch with timeless proportions.', ARRAY['Quartz movement','Gold-plated case','Roman numeral dial','Leather strap']),
  ('revelation-set', 'Révélation Sapphire Set', 'Necklaces', 5200, NULL, 5, 27, ARRAY['https://images.pexels.com/photos/32988651/pexels-photo-32988651.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7541801/pexels-photo-7541801.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/12133990/pexels-photo-12133990.jpeg?auto=compress&cs=tinysrgb&w=900'], 'White Gold', 'Sapphire', 'Statement Pieces', true, true, true, ARRAY['14"','16"','18"','20"'], 'A Ceylon sapphire pendant with a matching pair of drop earrings. Révélation is our atelier''s most ambitious set — a modern heirloom.', ARRAY['Ceylon sapphire, 3.1ct','Matching diamond drop earrings','18k white gold','Atelier-made to order'])
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  images = EXCLUDED.images,
  material = EXCLUDED.material,
  gemstone = EXCLUDED.gemstone,
  collection = EXCLUDED.collection,
  is_new = EXCLUDED.is_new,
  is_best_seller = EXCLUDED.is_best_seller,
  in_stock = EXCLUDED.in_stock,
  sizes = EXCLUDED.sizes,
  description = EXCLUDED.description,
  details = EXCLUDED.details;
